variables:
  GIT_STRATEGY: clone

stages:
  - deploy

deploy-pdsb:
  stage: deploy
  only:
    - tags
  tags:
      - kubemas
  script:
    - echo $CI_JOB_TOKEN
    - echo $CI_PROJECT_ID
    - echo $CI_COMMIT_TAG
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "http://git.pdsb.id/api/v4/projects/$CI_PROJECT_ID/packages/composer"'

deploy-gitlab:
  stage: deploy
  only:
    - tags
  tags:
      - gitlab-org
  script:
    - echo $CI_JOB_TOKEN
    - echo $CI_PROJECT_ID
    - echo $CI_COMMIT_TAG
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
